name: Linters

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Rubocop Linter with exit code
      uses: andrewmcodes/rubocop-linter-action@rubocop-exit-code
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
